### ISSUE TITLE
Django Server need to implemented. 

### ISSUE THREAD

**Issue by sunil-kothiyal** [david-lev/pywa#47]
### Describe the bug

This is a great app for whatsapp APIs
Please add django sever to reach a better community,

**Comment by yehuda-lev** [comment]
Hey thanks. We are aware of that. It's on the [list of things to add.](https://github.com/david-lev/pywa#%EF%B8%8F-todo)

**Comment by scroogeT** [comment]
Thanks @yehuda-lev for the reassurance, when can we expect Django to be supported ?

I'm working on adding WhatsApp support for a Daily Finance Quiz App running on a Django Backend but not sure if I should use the normal Django Rest Framework for the callback or wait for official Django support.

I'd be eternally grateful if the handlers & decorators Support Django out of the box soon 👍

**Comment by david-lev** [comment]
The Django framework is not like all other web frameworks (flask, fadtapi etc), and its routes structure works in a different way, therefore supporting the library requires thinking about how to perform the automatic registration of the webhook without special configuration on the part of the user.
We'd love to get ideas on how to add Django support :)

**Comment by david-lev** [comment]
Hi @scroogeT 
Try use this https://pywa.readthedocs.io/en/latest/content/client/client_reference.html#pywa.client.WhatsApp.webhook_update_handler
and this https://pywa.readthedocs.io/en/latest/content/client/client_reference.html#pywa.client.WhatsApp.webhook_challenge_handler
