### ISSUE TITLE
Error 404 on Webhook Verification with Flask Integration

### ISSUE THREAD

**Issue by julianobergamo** [david-lev/pywa#62]
Description

While integrating the pywa library with a Flask server, the webhook verification step results in a 404 error. The following message appears in the log:

`"GET /webhook/?hub.mode=subscribe&hub.challenge=<challange>&hub.verify_token=<verify_token> HTTP/1.1" 404`

Steps to Reproduce

    Configure the pywa library with the necessary credentials and a callback URL using pagekite.me.
    Start the Flask server.
    Observe the 404 error in the server logs when WhatsApp attempts to verify the webhook.

Expected Behavior

The server should correctly handle the GET request for webhook verification, respond with the challenge code provided by WhatsApp, and handle incoming POST requests for messages.

Actual Behavior

The server returns a 404 error during the GET request for webhook verification.

Example Code

Here is a simplified version of the code used to set up the Flask server and pywa integration:

```
from pywa import WhatsApp
from pywa.types import Message
from flask import Flask

flask_app = Flask(__name__)

wa = WhatsApp(
    phone_id='your_phone_id',
    token='your_token',
    server=flask_app,
    callback_url='https://your_pagekit.mel/webhook/',
    verify_token='your_verify_token',
    app_id='your_app_id',
    app_secret='your_app_secret',
)

@wa.on_message()
async def message_handler(_: WhatsApp, msg: Message):
    print(msg)

if __name__ == '__main__':
    flask_app.run(port=8000, debug=True)
```

Analysis

The issue arises because the pywa library does not automatically handle the webhook verification step, and there is no clear guidance in the documentation on how to configure Flask to handle this correctly. The workaround involves manually adding a route in Flask to handle the GET request for verification.

Proposed Solution

-     Documentation Update: Include clear instructions and example code in the pywa documentation for handling webhook verification with Flask.
-     Library Enhancement: Consider adding a method or functionality within pywa to automatically handle the webhook verification process, simplifying integration with web frameworks like Flask.

Additional Context

    pywa Version: 1.20.2
    Flask Version: 3.0.3
    Python Version: 3.10.12
    Operating System: Linux Mint 21.1

This issue is critical for developers attempting to integrate pywa with Flask, as it hinders the initial setup and functionality testing.

**Comment by david-lev** [comment]
Hi @julianobergamo, thanks for the report.
If you register the callback url to a different endpoint other than "/", you need to tell pywa to register the route for this endpoint. so in your code move the endpoint to `webhook_endpoint`:

```python
wa = WhatsApp(
    phone_id='your_phone_id',
    token='your_token',
    server=flask_app,
    callback_url='https://your_pagekit.mel',
    webhook_endpoint='/webhook',
    verify_token='your_verify_token',
    app_id='your_app_id',
    app_secret='your_app_secret',
)
```
I will soon try to add a separate guide for flask and even for django and others

**Comment by julianobergamo** [comment]
Hey david-lev,
Thanks a lot for helping me out with this issue. Your response really helped me!
Thanks again!
