### ISSUE TITLE
send_audio lacks the reply_to_message_id parameter

### ISSUE THREAD

**Issue by ArielS1** [david-lev/pywa#73]
### Describe the bug

I'm unable to send an audio message as a reply to another message while it is possible to do it from my user client

**Comment by ArielS1** [comment]
i fixed it here in [this PR](https://github.com/david-lev/pywa/pull/74)

**Comment by david-lev** [comment]
> i fixed it here in [this PR](https://github.com/david-lev/pywa/pull/74)

Hi @ArielS1, thanks for your contribution!
Is this got checked and worked? in the facebook docs appear that some messages cannot be sent as replies
